USE Ecommerce;
DROP PROCEDURE IF EXISTS DeleteSuscription;
DELIMITER //

CREATE PROCEDURE DeleteSuscription(IN IdUser_parameter INT)
BEGIN
 DELETE FROM SUSCRIPTION WHERE SUSCRIPTION.Id_User_FK = IdUser_parameter;

END //

DELIMITER ;

