USE Ecommerce;

SELECT
	Firts_Name
FROM
	user
;

SELECT *FROM USER;
SELECT *FROM USER_TYPE;
SELECT *FROM USER_USER_TYPE;
SELECT *FROM PRODUCT;
SELECT *FROM CATEGORY;
SELECT *FROM STATE;
SELECT *FROM DEPARTMENT;

SELECT PRODUCT.Name, PRODUCT.Brand, PRODUCT.Cost , PRODUCT.Description FROM PRODUCT WHERE Id_Category_FK=9;