DROP DATABASE IF EXISTS Ecommerce;

CREATE DATABASE Ecommerce;

USE Ecommerce;

CREATE TABLE IF NOT EXISTS TOKEN(
Id INTEGER PRIMARY KEY AUTO_INCREMENT,
Code_Token VARCHAR (200) NOT NULL,
Creation_Date DATETIME
);


CREATE TABLE IF NOT EXISTS USER(
Id INTEGER PRIMARY KEY AUTO_INCREMENT,
Firts_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
Email VARCHAR(40) NOT NULL,
Address VARCHAR(150) NOT NULL,
Token INTEGER NOT NULL, 
FOREIGN KEY(Token) REFERENCES TOKEN(Id),
Password VARCHAR(30)
);


USE Ecommerce;
CREATE TABLE IF NOt EXISTS USER_TYPE(
Id_User_Type INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Description VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_USER_TYPE(
Id INTEGER PRIMARY KEY,
Id_User INTEGER , FOREIGN KEY (Id) REFERENCES USER(Id),
Id_User_Type INTEGER, FOREIGN KEY (Id_User_Type) REFERENCES USER_TYPE(Id_User_Type)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT(
Id INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORY(
Id INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Description VARCHAR(100) NOT NULL,
Department INTEGER , FOREIGN KEY (Id) REFERENCES DEPARTMENT(Id)
);


CREATE TABLE IF NOT EXISTS PRODUCT(
Id INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Type VARCHAR(30) NOT NULL,
Cost DECIMAL ,
Description VARCHAR(50) NOT NULL,
Id_Category INT , FOREIGN KEY (Id) REFERENCES CATEGORY(Id),
Id_Users Int ,FOREIGN KEY (Id) REFERENCES USER(Id),
Image VARCHAR (100) NOT NULL
);


CREATE TABLE CALIFICACIONES (
Id INTEGER PRIMARY KEY,
Id_Users_Client INT, FOREIGN KEY (Id) REFERENCES USER(Id),
Id_Users_Seller INT, FOREIGN KEY (Id) REFERENCES USER(Id),
N_Qualification INT NOT NULL
);


