DROP DATABASE IF EXISTS Ecommerce;

CREATE DATABASE Ecommerce;

USE Ecommerce;

CREATE TABLE IF NOT EXISTS USER(
Id INTEGER PRIMARY KEY AUTO_INCREMENT,
Firts_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
Email VARCHAR(40) NOT NULL,
Address VARCHAR(150) NOT NULL,
Password VARCHAR(30),
Check_Email BOOLEAN
);



USE Ecommerce;
CREATE TABLE IF NOt EXISTS USER_TYPE(
Id_User_Type INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Description VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_USER_TYPE(
Id INTEGER PRIMARY KEY,
Id_User_FK INTEGER , FOREIGN KEY (Id_User_FK) REFERENCES USER(Id),
Id_User_Type_FK INTEGER, FOREIGN KEY (Id_User_Type_FK) REFERENCES USER_TYPE(Id_User_Type)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT(
Id INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORY(
Id INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Description VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS STATE(
Id INTEGER PRIMARY KEY,
Name VARCHAR(45)
);


CREATE TABLE IF NOT EXISTS PRODUCT(
Id INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Brand VARCHAR(30) NOT NULL,
Cost DECIMAL,
Description VARCHAR(50) NOT NULL,
Id_Category_FK INT , FOREIGN KEY (Id_Category_FK) REFERENCES CATEGORY(Id),
Id_User_FK INT ,FOREIGN KEY (Id_User_FK) REFERENCES USER(Id),
Image VARCHAR (100) NOT NULL ,
Date_Product DATE ,
Id_State_FK INT , FOREIGN KEY (Id_State_FK) REFERENCES STATE(Id),
Id_Department_FK Int ,FOREIGN KEY (Id_Department_FK) REFERENCES DEPARTMENT(Id)
);





CREATE TABLE CALIFICACIONES (
Id INTEGER PRIMARY KEY,
Id_Users_Client_FK INT, FOREIGN KEY (Id_Users_Client_FK) REFERENCES USER(Id),
Id_Users_Seller_FK INT, FOREIGN KEY (Id_Users_Seller_FK) REFERENCES USER(Id),
N_Qualification INT NOT NULL
);






