DROP DATABASE IF EXISTS Ecommerce;

CREATE DATABASE Ecommerce;

USE Ecommerce;

CREATE TABLE IF NOT EXISTS TOKEN(
Id INTEGER PRIMARY KEY AUTO_INCREMENT,
Code_Token VARCHAR (200) NOT NULL,
Creation_Date DATETIME
);


CREATE TABLE IF NOT EXISTS USER(
Id INTEGER PRIMARY KEY AUTO_INCREMENT,
Firts_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
Email VARCHAR(40) NOT NULL,
Address VARCHAR(150) NOT NULL,
Token INTEGER NOT NULL, 
FOREIGN KEY(Token) REFERENCES TOKEN(Id)
);


CREATE TABLE IF NOt EXISTS USER_TYPE(
Id_User_type INTEGER PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Description VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_USER_TYPE(
Id INTEGER PRIMARY KEY,
Id_User INTEGER , FOREIGN KEY (Id) REFERENCES USER(Id),
Id_User_Type INTEGER, FOREIGN KEY (Id_User_Type) REFERENCES USER_TYPE(Id_User_Type)
);
