import {Product} from './product-model'

export const PRODUCTS: Product[] = [
  {
    Id: 1,
    Name: "ps5",
    Description: "Consola de videojuegos de ultima generacion",
    Price: 30000,
    State: 2,
    Img: "assets/imgs/ps5.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Automovil",
    Description: "Automovil ultimo modelo",
    Price: 500000,
    State: 2,
    Img: "assets/imgs/car.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "iphone",
    Description: "Smartphone de gama alta",
    Price: 20000,
    State: 2,
    Img: "assets/imgs/iphone.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Laptop",
    Description: "Laptop completamente nuevo y de buena calidad",
    Price: 35000,
    State: 2,
    Img: "assets/imgs/slaptop.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "ps5",
    Description: "Consola de videojuegos de ultima generacion",
    Price: 30000,
    State: 2,
    Img: "assets/imgs/ps5.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Automovil",
    Description: "Automovil ultimo modelo",
    Price: 500000,
    State: 2,
    Img: "assets/imgs/car.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "iphone",
    Description: "Smartphone de gama alta",
    Price: 20000,
    State: 2,
    Img: "assets/imgs/iphone.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Laptop",
    Description: "Laptop completamente nuevo y de buena calidad",
    Price: 35000,
    State: 2,
    Img: "assets/imgs/slaptop.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "ps5",
    Description: "Consola de videojuegos de ultima generacion",
    Price: 30000,
    State: 2,
    Img: "assets/imgs/ps5.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Automovil",
    Description: "Automovil ultimo modelo",
    Price: 500000,
    State: 2,
    Img: "assets/imgs/car.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "iphone",
    Description: "Smartphone de gama alta",
    Price: 20000,
    State: 2,
    Img: "assets/imgs/iphone.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Laptop",
    Description: "Laptop completamente nuevo y de buena calidad",
    Price: 35000,
    State: 2,
    Img: "assets/imgs/slaptop.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "ps5",
    Description: "Consola de videojuegos de ultima generacion",
    Price: 30000,
    State: 2,
    Img: "assets/imgs/ps5.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Automovil",
    Description: "Automovil ultimo modelo",
    Price: 500000,
    State: 2,
    Img: "assets/imgs/car.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "iphone",
    Description: "Smartphone de gama alta",
    Price: 20000,
    State: 2,
    Img: "assets/imgs/iphone.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Laptop",
    Description: "Laptop completamente nuevo y de buena calidad",
    Price: 35000,
    State: 2,
    Img: "assets/imgs/slaptop.png",
    Department: 1,
    Seller: 2,
    Category: 3,
  }
]

