import {Product} from './product-model'

export const PRODUCTS: Product[] = [
  {
    Id: 1,
    Name: "baleadas",
    Description: "baleadas goldstar",
    Price: 3000,
    State: 2,
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "carro",
    Description: "carro del anio",
    Price: 500000,
    State: 2,
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "mascarillas",
    Description: "para el covid",
    Price: 300,
    State: 2,
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Ducati",
    Description: "Moto completamente nueva",
    Price: 3000,
    State: 2,
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "baleadas",
    Description: "baleadas goldstar",
    Price: 3000,
    State: 2,
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "carro",
    Description: "carro del anio",
    Price: 500000,
    State: 2,
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "mascarillas",
    Description: "para el covid",
    Price: 300,
    State: 2,
    Department: 1,
    Seller: 2,
    Category: 3,
  },
  {
    Id: 1,
    Name: "Ducati",
    Description: "Moto completamente nueva",
    Price: 3000,
    State: 2,
    Department: 1,
    Seller: 2,
    Category: 3,
  }
]

